# This workflow will upload a Python Package to PyPI when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

name: Upload Python Package to PyPI

on:
  release:
    types: [published] # This workflow runs when a new GitHub release is published

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    # These permissions are mandatory for trusted publishing
    permissions:
      id-token: write # This is required for OIDC authentication
      contents: read  # This is required for checkout

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies and build tools
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine

    - name: Build package
      run: python setup.py sdist bdist_wheel

    - name: Publish package to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      # This action handles the OIDC authentication automatically.
      # No API token is needed.
